name: 'scribear-server'
services:
  whisper-service:
    image: scribear/whisper-service-cuda:main
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - API_KEY=${API_KEY}
    expose:
      - 80
    volumes:
      - ./device_config.json:/app/device_config.json
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]
              
  node-server:
    image: scribear/node-server:main
    build:
      context: ./node-server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - USE_HTTPS=${USE_HTTPS}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - WHISPER_SERVICE_ENDPOINT=ws://whisper-service:80/sourcesink
      - API_KEY=${API_KEY}
      - REQUIRE_AUTH=${REQUIRE_AUTH}
      - SOURCE_TOKEN=${SOURCE_TOKEN}
      - ACCESS_TOKEN_BYTES=${ACCESS_TOKEN_BYTES}
      - ACCESS_TOKEN_REFRESH_INTERVAL_SEC=${ACCESS_TOKEN_REFRESH_INTERVAL_SEC}
      - ACCESS_TOKEN_VALID_PERIOD_SEC=${ACCESS_TOKEN_VALID_PERIOD_SEC}
      - SESSION_TOKEN_BYTES=${SESSION_TOKEN_BYTES}
      - SESSION_LENGTH_SEC=${SESSION_LENGTH_SEC}
    ports:
      - "80"
    restart: unless-stopped

  frontend:
    depends_on:
      whisper-service:
        condition: service_healthy
      node-server:
        condition: service_healthy
    ports:
      - "80"
    image: scribear/frontend:master
    restart: unless-stopped