name: 'scribear-server'
services:
  whisper-service:
    image: scribear/whisper-service-cuda:main
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - API_KEY=${API_KEY}
    expose:
      - 80
    restart: unless-stopped

  node-server:
    image: scribear/node-server:main
    build:
      context: ./node-server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - USE_HTTPS=${USE_HTTPS}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - WHISPER_SERVICE_ENDPOINT=ws://whisper-service:80/whisper?api_key=${API_KEY}&model_key=${MODEL_KEY}
      - WHISPER_RECONNECT_INTERVAL_SEC=${WHISPER_RECONNECT_INTERVAL_SEC}
      - REQUIRE_AUTH=${REQUIRE_AUTH}
      - SOURCE_TOKEN=${SOURCE_TOKEN}
      - ACCESS_TOKEN_BYTES=${ACCESS_TOKEN_BYTES}
      - ACCESS_TOKEN_REFRESH_INTERVAL_SEC=${ACCESS_TOKEN_REFRESH_INTERVAL_SEC}
      - ACCESS_TOKEN_VALID_PERIOD_SEC=${ACCESS_TOKEN_VALID_PERIOD_SEC}
      - SESSION_TOKEN_BYTES=${SESSION_TOKEN_BYTES}
      - SESSION_LENGTH_SEC=${SESSION_LENGTH_SEC}
    ports:
      - ${NODE_PORT}:80
    volumes:
      - ${KEY_FILEPATH:-/dev/null}:/app/cert/key.pem
      - ${CERTIFICATE_FILEPATH:-/dev/null}:/app/cert/key.pem
    restart: unless-stopped

  frontend:
    depends_on:
      whisper-service:
        condition: service_healthy
      node-server:
        condition: service_healthy
    ports:
      - ${FRONTEND_PORT}:80
    image: scribear/frontend:master