services:
  caddy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/ssl/certs/engrit/dcl-1265-05.cs.illinois.edu.cer:/etc/caddy/pub.cert
      - /etc/ssl/private/engrit/dcl-1265-05.cs.illinois.edu.key:/etc/caddy/priv.key
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN}

volumes:
  caddy_data:
  caddy_config:
