name: 'Setup Node'
description: 'Checks out the repo and installs dependencies for node packages.'
inputs:
  # Inputs are the same as the arguments for irongut/CodeCoverageSummary@v1.3.0
  # All except filename have default values
  filename:
    required: true
  badge:
    default: true
  fail_below_min:
    default: false
  format:
    default: markdown
  hide_branch_rate:
    default: false
  hide_complexity:
    default: false
  indicators: 
    default: true
  output: 
    default: both
  thresholds: 
    default: '50 75'
runs:
  using: "composite"
  env:
    FILENAME: ${{ inputs.filename }}
    BADGE: ${{ inputs.badge }}
    FAIL_BELOW_MIN: ${{ inputs.fail_below_min }}
    FORMAT: ${{ inputs.format }}
    HIDE_BRANCH_RATE: ${{ inputs.hide_branch_rate }}
    HIDE_COMPLEXITY: ${{ inputs.hide_complexity }}
    INDICATORS: ${{ inputs.indicators }}
    OUTPUT: ${{ inputs.output }}
    THRESHOLDS: ${{ inputs.thresholds }}
  steps:
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ env.FILENAME }}
        badge: ${{ env.BADGE }}
        fail_below_min: ${{ env.FAIL_BELOW_MIN }}
        format: ${{ env.FORMAT }}
        hide_branch_rate: ${{ env.HIDE_BRANCH_RATE }}
        hide_complexity: ${{ env.HIDE_COMPLEXITY }}
        indicators: ${{ env.INDICATORS }}
        output: ${{ env.OUTPUTS }}
        thresholds: ${{ env.THRESHOLDS }}
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
