name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  node-version: 20

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Navigate to node-server
        run: cd node-server
  
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: 'node-server/package-lock.json'

      - name: Run tests
        run: npm run ci-test
      
  lint-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Navigate to node-server
        run: cd node-server
  
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: 'node-server/package-lock.json'

      - name: Run linter
        run: npm run lint

  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Navigate to node-server
        run: cd node-server
  
      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: 'node-server/package-lock.json'

      - name: Run build
        run: npm run build
