name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
  
      - name: Navigate to node-server
        run: cd node-server

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
  test-node:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm run ci-test
      
  lint-node:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: npm run lint

  build-node:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: npm run build
