name: node-server CI

on:
  push:
    paths:
      - node-server/**
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  node-version: 20

jobs:
  test-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: 'node-server'
        run: npm ci

      - name: Run tests
        working-directory: 'node-server'
        run: npm run ci-test
      
  lint-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: 'node-server'
        run: npm ci  

      - name: Run linter
        working-directory: 'node-server'
        run: npm run lint

  build-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: 'node-server'
        run: npm ci
  
      - name: Run build
        working-directory: 'node-server'
        run: npm run build

  build-container-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./node-server
          file: Dockerfile
          push: false
