name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  NODE_VERSION: 20

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-server
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run tests
        run: npm run ci-test
      
  lint-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-server
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run linter
        run: npm run lint

  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-server
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Run build
        run: npm run build
