name: Node CI

on:
  push:
    paths:
      - apps/*
      - libs/*
    branches:
      - main
      - staging
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  # Needed in order to add comments to PR
  pull-requests: write

jobs:
  check-formatting-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Check formatting
        working-directory: "."
        run: npm run format

  run-linter-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Check formatting
        working-directory: "."
        run: npm run lint

  run-build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run build
        working-directory: "."
        run: npm run build

  run-tests-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run build
        working-directory: "."
        run: npm run build

      - name: Run tests
        working-directory: "."
        run: npm run test

      - name: Code Coverage Report - Base Fastify Server
        uses: ./.github/actions/coverage-report
        with:
          package_name: "Base Fastify Server"
          filename: "./libs/base-fastify-server/coverage/cobertura-coverage.xml"

      - name: Code Coverage Report - Session Manager
        uses: ./.github/actions/coverage-report
        with:
          package_name: "Session Manager"
          filename: "./apps/session-manager/coverage/cobertura-coverage.xml"
