name: node-server CI

on:
  push:
    branches:
      - main
    paths:
      - node-server/**
  pull_request:
    branches:
      - main
    paths:
      - node-server/**
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  node-version: 20

jobs:
  test-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: 'node-server'
        run: npm ci

      - name: Run tests
        working-directory: 'node-server'
        run: npm run ci-test
      
  lint-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: 'node-server'
        run: npm ci  

      - name: Run linter
        working-directory: 'node-server'
        run: npm run lint

  build-node-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        working-directory: 'node-server'
        run: npm ci
  
      - name: Run build
        working-directory: 'node-server'
        run: npm run build
