name: whisper-service CI

on:
  push:
    paths:
      - whisper-service/**
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

env:
  python-version: 3.12

jobs:
  test-whisper-service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        working-directory: "whisper-service"
        run: "pip install -r requirements.txt"

      - name: Run tests
        working-directory: "whisper-service"
        run: pytest --cov=.

  lint-whisper-service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        working-directory: "whisper-service"
        run: "pip install -r requirements.txt"

      - name: Run tests
        working-directory: "whisper-service"
        run: pylint --disable=import-error $(git ls-files '*.py')


  build-cpu-container-whisper-service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./whisper-service
          file: Dockerfile_CPU
          push: false

  build-cuda-container-whisper-service:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./whisper-service
          file: Dockerfile_CUDA
          push: false
        